feat(anta): Add support for command blacklist to secure tests
arista-netdevops-community/anta pull request #416
Opened 2023-09-28 13:32 UTC by titom73

# Description

Add support of a list of blacklisted regex to secure test execution and avoid
any critical change on devices.

It currently blocked CLI with following regex

- Reload command: `^reload\s*\w*`
- Configure mode: `^conf\w*\s*(terminal|session)*`
- Write: `^wr\w*\s*\w+`

Fixes #423

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2023-09-28 15:13 UTC, gmuloc commented
This implementation won't prevent a malicious device implementation (injecting reload / conf t / ... in its own _collect.

Wondering if we should not rather implement this in the AntaDevice(ABC) collect ?

2023-09-28 15:24 UTC, titom73 commented on anta/models.py
> +                self.result.is_error(message="Test has blocked command")
Maybe better to state ANTA will protect tests and it would be a best practice to use a r/o user on EOS.

2023-09-28 15:36 UTC, mtache requested changes

2023-09-28 15:37 UTC, gmuloc commented
> This implementation won't prevent a malicious device implementation (injecting reload / conf t / ... in its own _collect.
> 
> Wondering if we should not rather implement this in the AntaDevice(ABC) collect ?

we keep it in test

2023-09-28 15:45 UTC, mtache requested changes

2023-09-28 15:45 UTC, mtache commented on anta/models.py
> +BLACKLIST_REGEX = [r"^reload.*", r"^conf\w*\s*(terminal|session)*", r"^wr\w*\s*\w+"]
You can add the following commands :)

```
clear isis database all
clear isis database level-1
clear isis database level-2
clear isis <instance> database 
```

2023-09-28 15:47 UTC, mtache requested changes

2023-09-28 15:47 UTC, mtache commented on anta/models.py
> +                self.result.is_error(message="Test has blocked command")
Move line 415 to `blocked` property and add command details in the message.

2023-10-02 18:01 UTC, carl-baillargeon reviewed
Tested a few blocked commands locally with `collect` of `AntaTest` and it works.

Should we add this guard to `anta debug` as well?
```
(.anta) ➜  anta git:(test_blacklist) anta debug run-cmd -c "configure terminal" -d DC1-LEAF1A --ofmt text
Run command configure terminal on DC1-LEAF1A

(.anta) ➜  anta git:(test_blacklist) anta debug run-cmd -c "write" -d DC1-LEAF1A
Run command write on DC1-LEAF1A
{'messages': ['Copy completed successfully.']}
```

2023-10-03 06:09 UTC, titom73 commented
> Tested a few blocked commands locally with `collect` of `AntaTest` and it works.
> 
> Should we add this guard to `anta debug` as well?
> 
> ```
> (.anta) ➜  anta git:(test_blacklist) anta debug run-cmd -c "configure terminal" -d DC1-LEAF1A --ofmt text
> Run command configure terminal on DC1-LEAF1A
> 
> (.anta) ➜  anta git:(test_blacklist) anta debug run-cmd -c "write" -d DC1-LEAF1A
> Run command write on DC1-LEAF1A
> {'messages': ['Copy completed successfully.']}
> ```

Ideas was to protect tests to send dangerous command while in debug mode, you do that on purpose. A complete protection of the device should be done via a correct RBAC configuration.

Adding this protection to `anta debug` can be done but in different manner than process in place for `anta nrfu`

2023-10-03 12:18 UTC, carl-baillargeon approved these changes
LGTM

2023-10-03 12:26 UTC, gmuloc approved these changes

2023-10-04 07:26 UTC, merged