Feat: Added test case for SSL certificate status as VerifyCertificateStatus
arista-netdevops-community/anta pull request #472
Opened 2023-11-21 06:09 UTC by MaheshGSLAB

# Description

Add the test case to verify the ssl certificate expiry, subject name, encryption type and size.

Run the testcase by adding catalog as below:
```
anta.tests.security:
  - VerifyCertificateStatus:
      certificate: capi.pem
      expiry_limit: 30
      subject_name: self.signed
      encryption: RSA
      size: 2048
```

1. Testcase pass when all details are correct:
```
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device  ┃ Test Name               ┃ Test Status ┃ Message(s) ┃ Test description                 ┃ Test category ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ spine01 │ VerifyCertificateStatus │ success     │            │ Verifies SSL certificate status. │ security      │
└─────────┴─────────────────────────┴─────────────┴────────────┴──────────────────────────────────┴───────────────┘
```

2. Testcase fails when details are incorrect:
```
                                                                                 All tests results                                                                                   
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device  ┃ Test Name               ┃ Test Status ┃ Message(s)                                                                    ┃ Test description                 ┃ Test category ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ spine01 │ VerifyCertificateStatus │ failure     │ SSL certificate `capi.pem` is expired.                                        │ Verifies SSL certificate status. │ security      │
│         │                         │             │ Subject name `test1` is not found for SSL certificate `capi.pem`.             │                                  │               │
│         │                         │             │ Encryption algorithm `DSA` is not found for SSL certificate `capi.pem`.       │                                  │               │
│         │                         │             │ Encryption algorithm size `2048` is not found for SSL certificate `capi.pem`. │                                  │               │
│         │                         │             │                                                                               │                                  │               │
└─────────┴─────────────────────────┴─────────────┴───────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴───────────────┘
```

Fixes #470 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2023-11-23 22:28 UTC, carl-baillargeon requested changes

2023-11-23 22:28 UTC, carl-baillargeon commented on anta/tests/security.py
> +        try:
Avoid large try-except blocks. You can use the `anta.tools.get_value` function:
```
if (certificate_data := get_value(certificate_output, f"certificates..{self.inputs.certificate}", separator="..")) is None:
    self.result.is_failure(f"SSL certificate '{self.inputs.certificate}', is not configured.")
    return
```

2023-11-23 22:28 UTC, carl-baillargeon commented on anta/tests/security.py
> +            day_difference = (datetime.datetime.utcfromtimestamp(expiry_time) - datetime.datetime.utcfromtimestamp(current_timestamp)).days
Please use `datetime.datetime.fromtimestamp()`

https://docs.python.org/3/library/datetime.html#aware-and-naive-objects

2023-11-23 22:28 UTC, carl-baillargeon commented on anta/tests/security.py
> +            self.result.is_failure(failure_msg) if failure_msg else self.result.is_success()
When verifying multiple inputs, you can build a dictionary with the results and have that dictionary in the failure message. You can refer to `VerifyMlagDualPrimary` test as an example.

2023-11-23 22:28 UTC, carl-baillargeon commented on anta/tests/security.py
Can you also add unit test for the new test please? It would be under `anta/tests/units/anta_tests/test_security`

https://www.anta.ninja/stable/contribution/#unit-tests

2023-11-23 22:28 UTC, carl-baillargeon commented on anta/tests/security.py
> +import datetime
Please import only what you need. `from datetime import <>`

2023-11-23 22:30 UTC, carl-baillargeon commented
Thank you @MaheshGSLAB for the PR. I left some comments, feel free to reach out if you have any questions! We can also schedule a call if needed.

2023-12-01 13:05 UTC, MaheshGSLAB commented
> Thank you @MaheshGSLAB for the PR. I left some comments, feel free to reach out if you have any questions! We can also schedule a call if needed.

Thanks @carl-baillargeon for the suggestion. I have update the code with mandate encryption type and size as user input. I know we discussed about optional, in next commit i will add the support for the same.

2024-01-06 14:42 UTC, carl-baillargeon requested changes

2024-01-06 14:42 UTC, carl-baillargeon commented on anta/custom_types.py
> +EncryptionSize = Literal[1024, 2048, 4096]
I would call this `KeySize`. Also, RSA and ECDSA have different key size options:
```bash
DC1-LEAF1A(config)#security pki key generate rsa ?
  2048  Use 2048-bit keys
  3072  Use 3072-bit keys
  4096  Use 4096-bit keys
```
```bash
DC1-LEAF1A(config)#security pki key generate ecdsa ?
  prime256v1  X9.62/SECG curve over a 256 bit prime field (P-256)
  secp384r1   NIST/SECG curve over a 384 bit prime field (P-384)
  secp521r1   NIST/SECG curve over a 521 bit prime field (P-521)
```

2024-01-06 14:42 UTC, carl-baillargeon commented on anta/custom_types.py
> +EncryptionType = Literal["RSA", "ECDSA"]
Let's call this `EncryptionAlgorithm`

2024-01-06 14:42 UTC, carl-baillargeon commented on anta/tools/utils.py
> +from typing import Any, Dict
Please always try to use the built-ins dict, list, etc.
https://peps.python.org/pep-0585/

2024-01-08 13:35 UTC, MaheshGSLAB commented on anta/tools/utils.py
> +            failed_logs.append(f"\nExpected {element} is `{expected_data}` however in actual found as `{actual_data}`.")
Expected `1048` as key.size, but found `1024` instead.

2024-01-10 02:36 UTC, carl-baillargeon requested changes

2024-01-10 02:36 UTC, carl-baillargeon commented on anta/tests/security.py
> +            key_size: int
```suggestion
            key_size: Union[RsaKeySize, EcdsaKeySize]
```

2024-01-10 02:36 UTC, carl-baillargeon commented on anta/tests/security.py
> +        certificates: list[APISSLCertificates]
```suggestion
        certificates: List[APISSLCertificates]
```
I think CI is failing because of that. Please confirm

2024-01-10 15:46 UTC, gmuloc approved these changes
LGTM - would be nice to add unit test for the tool funciton

2024-01-10 15:46 UTC, gmuloc commented on anta/tools/utils.py
> +def get_failed_logs(expected_output: dict[Any, Any], actual_output: dict[Any, Any]) -> str:
do we have unit test for this?

2024-01-10 15:58 UTC, carl-baillargeon approved these changes
LGTM

2024-01-10 21:44 UTC, merged