feat: Adding the test case to verify BGP neighbor authentication
arista-netdevops-community/anta pull request #495
Opened 2023-12-14 06:10 UTC by MaheshGSLAB

# Description

Add the test case to verify the BGP neighbor authentication.

Run the testcase by adding catalog as below:
```
anta.tests.routing:
  bgp:
      - VerifyBGPAuthentication:
          bgp_neighbors:
            - neighbor: 172.30.11.1
              vrf: default
            - neighbor: 172.30.11.5
              vrf: default
```

1. Testcase pass when details are correct.
```
                                                        All tests results                                                         
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device    ┃ Test Name               ┃ Test Status ┃ Message(s) ┃ Test description                               ┃ Test category ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ s1-spine1 │ VerifyBGPAuthentication │ success     │            │ Verifies if BGP neighbors are configured with  │ routing, bgp  │
│           │                         │             │            │ MD5 authentication and state as established in │               │
│           │                         │             │            │ the specified VRF.                             │               │
└───────────┴─────────────────────────┴─────────────┴────────────┴────────────────────────────────────────────────┴───────────────┘
```

2. Testcase fails when bgp neighbor not found.
```
                                                        All tests results                                                         
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device    ┃ Test Name               ┃ Test Status ┃ Message(s)                   ┃ Test description             ┃ Test category ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ s1-spine1 │ VerifyBGPAuthentication │ failure     │ BGP neighbor 172.30.11.11 is │ Verifies if BGP neighbors    │ routing, bgp  │
│           │                         │             │ not configured for `default` │ are configured with MD5      │               │
│           │                         │             │ VRF.                         │ authentication and state as  │               │
│           │                         │             │                              │ established in the specified │               │
│           │                         │             │                              │ VRF.                         │               │
└───────────┴─────────────────────────┴─────────────┴──────────────────────────────┴──────────────────────────────┴───────────────┘
```

3. Testcase fails when MD5 authentication is not enabled and state is not establised
```
                                                        All tests results                                                         
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Device    ┃ Test Name               ┃ Test Status ┃ Message(s)                   ┃ Test description             ┃ Test category ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ s1-spine1 │ VerifyBGPAuthentication │ failure     │ Following BGP neighbors are  │ Verifies if BGP neighbors    │ routing, bgp  │
│           │                         │             │ not established or MD5       │ are configured with MD5      │               │
│           │                         │             │ authentication not enabled:  │ authentication and state as  │               │
│           │                         │             │ {'bgp_neighbors':            │ established in the specified │               │
│           │                         │             │ {'default': {'172.30.11.11': │ VRF.                         │               │
│           │                         │             │ {'state': 'Idle',            │                              │               │
│           │                         │             │ 'md5_auth_enabled': False},  │                              │               │
│           │                         │             │ '172.30.11.51': {'state':    │                              │               │
│           │                         │             │ 'Idle', 'md5_auth_enabled':  │                              │               │
│           │                         │             │ False}}}}                    │                              │               │
└───────────┴─────────────────────────┴─────────────┴──────────────────────────────┴──────────────────────────────┴───────────────┘
```

Fixes #493 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2023-12-20 14:10 UTC, carl-baillargeon requested changes

2023-12-20 14:10 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +class VerifyBGPAuthentication(AntaTest):
Since we only support MD5 in this test, I would call it something like `VerifyBGPMD5Auth` or something and adjust the docstring accordingly.

2023-12-20 14:10 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +class VerifyBGPAuthentication(AntaTest):
Or maybe `VerifyBGPNeighborMD5Auth`

2023-12-21 11:50 UTC, MaheshGSLAB commented on anta/tests/routing/bgp.py
> +            if bgp_output["state"] != "Established" or not bgp_output["md5AuthEnabled"]:
updated the logic to handle this case. Thanks

2024-01-24 16:11 UTC, carl-baillargeon approved these changes
LGTM after small adjustments in docstrings.

2024-01-24 16:11 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +        Input parameters of the testcase.
```suggestion
        Input parameters of the test case.
```

2024-01-24 16:11 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +        * failure: The test will fail if BGP peers are not found, state is not as established and MD5 authentication is not enabled in the specified VRF.
```suggestion
        * failure: The test will fail if BGP peers are not found, state is not as established or MD5 authentication is not enabled in the specified VRF.
```

2024-01-25 06:05 UTC, MaheshGSLAB commented on anta/tests/routing/bgp.py
> +        Input parameters of the testcase.
fixed

2024-01-25 06:05 UTC, MaheshGSLAB commented on anta/tests/routing/bgp.py
> +        * failure: The test will fail if BGP peers are not found, state is not as established and MD5 authentication is not enabled in the specified VRF.
fixed

2024-02-05 15:09 UTC, titom73 approved these changes
Looks good to me

2024-02-07 14:32 UTC, merged