feat: Adding the test case to verify BGP timers
arista-netdevops-community/anta pull request #510
Opened 2024-01-03 14:08 UTC by MaheshGSLAB

# Description

Adding the test case to verify BGP timers

Fixes #509 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-01-05 22:42 UTC, carl-baillargeon requested changes

2024-01-05 22:42 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +            if not (bgp_output := get_value(self.instance_commands[0].json_output, f"vrfs..{vrf}..peerList", separator="..")):
Do you need to use `separator=".."` here?

2024-01-05 22:42 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +                failures[str(peer_address)] = {vrf: "Not configured"}
`peer_address` is already a `str` no?

2024-01-05 22:42 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +    commands = [AntaCommand(command="show bgp neighbors")]
`show bgp neighbors` will give you the neighbors of the default VRF only. You should use `show bgp neighbors vrf all` or use `AntaTemplate` and `show bgp neighbors vrf {vrf}`.

2024-01-05 22:42 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +            bgp_index = create_index(bgp_output, "peerAddress")
Can you check if the [get_item](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/plugins/plugin_utils/utils/get_item.py) function in AVD does what you want? If so, let's copy the code in `anta.tools` so we can use it.

2024-01-05 22:42 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +                failures[str(peer_address)] = {vrf: "Not configured"}
Why do we need a second statement here if there peer is not configured?

2024-01-29 19:08 UTC, carl-baillargeon approved these changes
LGTM after restricting `int` inputs.

2024-01-29 19:08 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +            hold_time: int
```suggestion
            hold_time: int = Field(ge=3, le=7200)
```

2024-01-29 19:08 UTC, carl-baillargeon commented on anta/tests/routing/bgp.py
> +            keep_alive_time: int
```suggestion
            keep_alive_time: int = Field(ge=0, le=3600)
```

2024-02-07 14:39 UTC, titom73 approved these changes

2024-02-14 01:18 UTC, merged