feat(anta.tests): Added testcase to verify ip address on interface
arista-netdevops-community/anta pull request #548
Opened 2024-01-29 10:50 UTC by MaheshGSLAB

# Description

Added testcase to verify ip address(primary and secondary) on interface.

Fixes #545 

Expected Results:
        * success: The test will pass if an interface is configured with a correct primary and secondary IPv4 address.
        * failure: The test will fail if an interface is not found or the primary and secondary IPv4 addresses do not match with the input.

Note: There is no optional input. All the input is required and restricted with values. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have run pre-commit for code linting and typing (`pre-commit run`)
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (`tox -e testenv`)

2024-01-29 11:15 UTC, MaheshGSLAB commented on anta/tests/interfaces.py
> +            if not (interface_output := get_value(command.json_output, f"interfaces..{intf}..interfaceAddress", separator="..")):
need to remove separatpr

2024-02-22 00:12 UTC, carl-baillargeon requested changes

2024-02-22 00:12 UTC, carl-baillargeon commented on anta/tests/interfaces.py
> +        interfaces: List[Interfaces]
```suggestion
        interfaces: List[InterfaceDetail]
```

2024-02-22 00:12 UTC, carl-baillargeon commented on anta/tests/interfaces.py
> +            secondary_ips: List[IPv4Network]
`secondary_ips` should be optional. Only check them if they are provided.

2024-02-23 13:19 UTC, merged